version: '3.7'

services:
  web:
    build:
        docker:
          web: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8001
    env_file:
      - ./.env.dev